//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRoomsUsers
    {
        public int User_ID { get; set; }
        public int ClassRoom_ID { get; set; }
        public byte Status { get; set; }
    
        public virtual ClassRoom ClassRoom { get; set; }
        public virtual User User { get; set; }
    }
}
