//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShareClassEntities : DbContext
    {
        public ShareClassEntities()
            : base("name=ShareClassEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassRoom> ClassRoom { get; set; }
        public virtual DbSet<ClassRoomsUsers> ClassRoomsUsers { get; set; }
        public virtual DbSet<HomeTask> HomeTask { get; set; }
        public virtual DbSet<HomeTask_File> HomeTask_File { get; set; }
        public virtual DbSet<Reaction> Reaction { get; set; }
        public virtual DbSet<ReactionType> ReactionType { get; set; }
        public virtual DbSet<Solution> Solution { get; set; }
        public virtual DbSet<Solution_File> Solution_File { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
