//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reaction
    {
        public int ID { get; set; }
        public int Reaction_Type { get; set; }
        public int Solution_ID { get; set; }
        public int User_ID { get; set; }
    
        public virtual ReactionType ReactionType { get; set; }
        public virtual Solution Solution { get; set; }
        public virtual User User { get; set; }
    }
}
